/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menuElement;

import javax.swing.JMenuItem;

/**
 *
 * @author ASUS
 */
public class MenuToolbar extends javax.swing.JFrame {

    /**
     * Creates new form MenuToolbar
     */
    public MenuToolbar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonOpener = new javax.swing.JButton();
        buttonMenuAdd = new javax.swing.JButton();
        textboxtNama = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuOpener = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonOpener.setText("Try Open");
        buttonOpener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenerActionPerformed(evt);
            }
        });
        getContentPane().add(buttonOpener, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 110, 52));

        buttonMenuAdd.setText("Add Another Menu");
        buttonMenuAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenuAddActionPerformed(evt);
            }
        });
        getContentPane().add(buttonMenuAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 150, 30));
        getContentPane().add(textboxtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 120, 120, 30));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file.png"))); // NOI18N
        jMenu1.setText("File");

        menuOpener.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuOpener.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdf.png"))); // NOI18N
        menuOpener.setText("Open Manual");
        jMenu1.add(menuOpener);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/config.png"))); // NOI18N
        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOpenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenerActionPerformed
        menuOpener.setEnabled(!menuOpener.isEnabled());
    }//GEN-LAST:event_buttonOpenerActionPerformed

    private void buttonMenuAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMenuAddActionPerformed
        JMenuItem menuBaru = new JMenuItem();

        menuBaru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ai.png"))); // NOI18N

        menuBaru.setText(textboxtNama.getText());

        jMenu2.add(menuBaru);
    }//GEN-LAST:event_buttonMenuAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuToolbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuToolbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuToolbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuToolbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuToolbar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonMenuAdd;
    private javax.swing.JButton buttonOpener;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuOpener;
    private javax.swing.JTextField textboxtNama;
    // End of variables declaration//GEN-END:variables
}
